
spring.jackson.serialization.INDENT_OUTPUT: true

#Server port
server:
  port: 8082
  servlet:
    #Seteamos el contexto para llamarlo http://localhost:8080/seido/xxxx
    context-path: /seido/

spring:
  application:
    name: jenkins-service-api
  profiles:
    #http://localhost:8081/seido/swagger-ui.html
    active: swagger
  cloud:
    config:
      enabled: true
  logging:
    level:
      ROOT: DEBUG
      com.seido.micro.core: DEBUG
      org.hibernate: WARN
      #type: trace

  # Configuración de la base de datos
  datasource:
    url: jdbc:postgresql://localhost:5432/seido_manager
    username: admin_db
    password: admin_12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  # Configuración de Flyway
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

jenkins:
  url: http://localhost:8080
  username: jenkins
  password: Pallas33
  #11139b6e7f738ad4282c257e245dba1ab6


---
spring:
  profiles: test

  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
      dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: dam
    password: dam

    platform: h2
    initialize: true

  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
