version: '3.8'

services:
  postgres:
    image: "postgres:13"
    restart: always
    environment:
      - POSTGRES_DB=seido_manager
      - POSTGRES_USER=admin_db
      - POSTGRES_PASSWORD=admin_12345678
    ports:
      - 5432:5432
    volumes:
      - seidopg-data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4:6.18
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - seidopgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_USER=admin
      - JENKINS_PASS=
      - JENKINS_INSTALL_PLUGINS=build-with-parameters:latest,github:latest,git:latest,customize-build-now:latest
    restart: always

  jenkins-service-api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-service-api  # Cambia el nombre del contenedor
    ports:
      - "8081:8081"

volumes:
  seidopg-data:
  seidopgadmin-data:
  jenkins-data:
